### ISSUE TITLE
SourceAssets tab does not actually show all assets.

### ISSUE THREAD

**Issue by rafaelf82** [Unity-Technologies/BuildReportInspector#1]
SourceAssets tab does not actually show all assets.

E.g.: When you a make a build with hundreds of textures the source assets only show about 30 of them and then the list gets truncated.

Tested on Unity 2019.2.11f1 and Build Report Inspector version 0.1.0

**Comment by Maesla** [comment]
In my case, using Unity 2019.3.5f1 and Build Inspector 0.1.2, SourceAssets tab is totally blank

Using #4 , everything seems to work
