### ISSUE TITLE
unity 2019.3 Build Report Inspector broken

### ISSUE THREAD

**Issue by afshinunity** [Unity-Technologies/BuildReportInspector#14]
https://forum.unity.com/threads/2019-3-build-report-inspector-broken.837430/

v0.1.2 not working.
using unity 2019.3.14

when can we see a fix for this? 
or it's not going to be released in package manager anymore and we should use this one from github?

**Comment by vaidas-unity** [comment]
This bug should no longer occur in v0.2.2-preview release of the package.
