### ISSUE TITLE
Provide a package version including Mobile Support

### ISSUE THREAD

**Issue by Wilfrid-Unity** [Unity-Technologies/BuildReportInspector#9]
Now that @vaidas-unity 's [pull request for Mobile Support](https://github.com/Unity-Technologies/BuildReportInspector/pull/7) was merged to master, it would be good to have the feature available in a new version of the package.

I tried to run the UPM C.I Tests job, and it looks that currently there are [issues related to npm version](https://yamato.prd.cds.internal.unity3d.com/jobs/518-com.unity.build-report-inspector/tree/master/.yamato%252Fupm-ci.yml%2523test_trigger/2003295/job).

**Comment by vaidas-unity** [comment]
> Now that @vaidas-unity 's [pull request for Mobile Support](https://github.com/Unity-Technologies/BuildReportInspector/pull/7) was merged to master, it would be good to have the feature available in a new version of the package.
> 
> I tried to run the UPM C.I Tests job, and it looks that currently there are [issues related to npm version](https://yamato.prd.cds.internal.unity3d.com/jobs/518-com.unity.build-report-inspector/tree/master/.yamato%252Fupm-ci.yml%2523test_trigger/2003295/job).

Fixed in #10

**Comment by vaidas-unity** [comment]
Done - published v0.2.2-preview

**Comment by Wilfrid-Unity** [comment]
Thanks Vaidas.

Does that version also include fixes for the issue reported here?
https://github.com/Unity-Technologies/BuildReportInspector/issues/14
https://forum.unity.com/threads/2019-3-build-report-inspector-broken.837430/
